baseURL = "https://www.technologytoolbox.com/"
languageCode = "en-us"
title = "Technology Toolbox"
theme = "techtoolbox-hugo"

enableGitInfo = true

[markup]
  [markup.highlight]
    noClasses = false # Use class attributes for code syntax highlighting

  [markup.goldmark.renderer]
    unsafe= true

[menu]

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services"
    weight = 10

  [[menu.main]]
    identifier = "company"
    name = "Company"
    url = "/company"
    weight = 20

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/jjameson"
    weight = 30

[permalinks]
  categories = "/blog/jjameson/category/:title/"

[social]
  github = "technology-toolbox"
  twitter = "techtoolbox_"

[server]
[[server.headers]]
  for = '/**'
  [server.headers.values]
    X-Frame-Options = 'DENY'