baseURL = "https://www.technologytoolbox.com/"
languageCode = "en-us"
title = "Technology Toolbox"
theme = "techtoolbox-hugo"

enableGitInfo = true

[markup]
  [markup.highlight]
    noClasses = false # Use class attributes for code syntax highlighting

  [markup.goldmark.renderer]
    unsafe= true

[menu]

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services"
    weight = 10

  [[menu.main]]
    identifier = "company"
    name = "Company"
    url = "/company"
    weight = 20

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/jjameson"
    weight = 30

[permalinks]
  categories = "/blog/jjameson/category/:title/"

[social]
  github = "technology-toolbox"
  twitter = "techtoolbox_"

[server]
[[server.headers]]
  for = '/**'
  [server.headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://www.google-analytics.com; img-src 'self' data: https://*.technologytoolbox.com https://www.google-analytics.com; script-src 'self' https://cdnjs.cloudflare.com https://www.google-analytics.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline';"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=()"
    X-Frame-Options = 'DENY'
[[server.headers]]
  for = '/blog/**'
  [server.headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://commento.technologytoolbox.com ws://commento.technologytoolbox.com https://www.google-analytics.com; font-src 'self' https://commento.technologytoolbox.com; frame-src https://platform.twitter.com; img-src 'self' data: https://*.technologytoolbox.com https://www.google-analytics.com; script-src 'self' data: https://commento.technologytoolbox.com https://cdnjs.cloudflare.com https://www.google-analytics.com https://www.googletagmanager.com https://platform.twitter.com; style-src 'self' 'unsafe-inline' https://commento.technologytoolbox.com;"
[[server.headers]]
  for = '/search/**'
  [server.headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://www.google-analytics.com; frame-src https://cse.google.com; img-src 'self' data: clients1.google.com https://cse.google.com https://www.google.com https://www.googleapis.com https://www.google-analytics.com; script-src 'self' 'unsafe-eval' data: https://cdnjs.cloudflare.com cse.google.com https://www.google.com https://www.google-analytics.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://commento.technologytoolbox.com https://www.google.com;"