baseURL = "https://www.technologytoolbox.com/"
languageCode = "en-us"
title = "Technology Toolbox"
theme = "techtoolbox-hugo"

enableGitInfo = true

[markup]
  [markup.highlight]
    noClasses = false # Use class attributes for code syntax highlighting

  [markup.goldmark.renderer]
    unsafe= true

[menu]

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services"
    weight = 10

  [[menu.main]]
    identifier = "company"
    name = "Company"
    url = "/company"
    weight = 20

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/jjameson"
    weight = 30

[permalinks]
  categories = "/blog/jjameson/category/:title/"

[social]
  github = "technology-toolbox"
  twitter = "techtoolbox_"

[server]
[[server.headers]]
  for = '/**'
  [server.headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://commento.technologytoolbox.com ws://commento.technologytoolbox.com https://www.google-analytics.com; font-src 'self' data: https://commento.technologytoolbox.com https://cdnjs.cloudflare.com; frame-src https://platform.twitter.com; img-src 'self' data: https://*.technologytoolbox.com; script-src 'self' 'unsafe-inline' data: https://commento.technologytoolbox.com https://cdnjs.cloudflare.com https://www.google-analytics.com https://platform.twitter.com; style-src 'self' 'unsafe-inline' https://commento.technologytoolbox.com https://cdnjs.cloudflare.com;"
    X-Frame-Options = 'DENY'